up

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,7 +33,12 @@ jobs:
         run: cmake -S . -B build -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6 -DCMAKE_VERBOSE_MAKEFILE=ON
 
       - name: Build the project
-        run: cmake --build build --parallel 4 || (echo "::error :: Build failed" && exit 1)
+        run:  |
+          cmake --build build --parallel 4
+          if [ $? -ne 0 ]; then
+          echo "::error :: Build failed"
+          exit 1
+          fi
 
       - name: Run tests
         run: ctest --verbose
